import { TaskTemplate } from "./types";

export const APP_NAME = "FamilyFlow";

export const taskTemplates: TaskTemplate[] = [
  {
    id: "tpl-toys",
    title: "Ranger les jouets",
    description: "Remettre les jouets dans les bacs avant le diner.",
    category: "enfants",
    minAge: 4,
    roles: ["enfant", "ado"],
    baseFrequency: "quotidienne",
    estimatedMinutes: 10,
    difficulty: 1,
    preferredDayOffset: 0,
    points: 10
  },
  {
    id: "tpl-laundry-basket",
    title: "Mettre le linge sale au panier",
    description: "Verifier la chambre et deposer le linge sale au bon endroit.",
    category: "enfants",
    minAge: 4,
    maxAge: 11,
    roles: ["enfant"],
    baseFrequency: "quotidienne",
    estimatedMinutes: 5,
    difficulty: 1,
    preferredDayOffset: 0,
    points: 6
  },
  {
    id: "tpl-table",
    title: "Aider a mettre la table",
    description: "Installer les couverts et les verres pour toute la famille.",
    category: "cuisine",
    minAge: 6,
    roles: ["enfant", "ado"],
    baseFrequency: "quotidienne",
    estimatedMinutes: 10,
    difficulty: 1,
    householdSizeMin: 3,
    preferredDayOffset: 0,
    points: 10
  },
  {
    id: "tpl-schoolbag",
    title: "Vider le cartable",
    description: "Sortir les papiers, la boite a gouter et les devoirs a signer.",
    category: "routine",
    minAge: 6,
    maxAge: 12,
    roles: ["enfant"],
    childrenCountMin: 1,
    baseFrequency: "quotidienne",
    estimatedMinutes: 8,
    difficulty: 1,
    preferredDayOffset: 0,
    points: 8
  },
  {
    id: "tpl-room-reset",
    title: "Ranger la chambre express",
    description: "Faire un reset de 10 minutes pour garder la chambre agreable.",
    category: "enfants",
    minAge: 7,
    maxAge: 14,
    roles: ["enfant", "ado"],
    childrenCountMin: 1,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 15,
    difficulty: 2,
    preferredDayOffset: 2,
    points: 14
  },
  {
    id: "tpl-gourde",
    title: "Preparer la gourde et les affaires",
    description: "Gourde, tenue du lendemain et affaires d'ecole pretes avant le coucher.",
    category: "routine",
    minAge: 6,
    maxAge: 15,
    roles: ["enfant", "ado"],
    childrenCountMin: 1,
    baseFrequency: "quotidienne",
    estimatedMinutes: 7,
    difficulty: 1,
    preferredDayOffset: 0,
    points: 8
  },
  {
    id: "tpl-vacuum",
    title: "Passer l'aspirateur",
    description: "Nettoyer les pieces communes et l'entree.",
    category: "menage",
    minAge: 13,
    roles: ["ado", "parent", "adulte"],
    housingTypes: ["appartement", "maison"],
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 35,
    difficulty: 3,
    roomCountMin: 3,
    preferredDayOffset: 5,
    indirectCostPerMonth: 12,
    points: 35
  },
  {
    id: "tpl-floor",
    title: "Laver les sols",
    description: "Passer serpilliere ou balai humide dans les zones de passage.",
    category: "menage",
    minAge: 15,
    roles: ["ado", "parent", "adulte"],
    housingTypes: ["appartement", "maison"],
    roomCountMin: 4,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 35,
    difficulty: 3,
    preferredDayOffset: 5,
    indirectCostPerMonth: 10,
    points: 34
  },
  {
    id: "tpl-trash",
    title: "Sortir les poubelles",
    description: "Sortir le tri et les dechets menagers la veille du ramassage.",
    category: "entretien",
    minAge: 12,
    roles: ["ado", "parent", "adulte"],
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 12,
    difficulty: 2,
    preferredDayOffset: 3,
    indirectCostPerMonth: 4,
    points: 15
  },
  {
    id: "tpl-dishwasher",
    title: "Vider le lave-vaisselle",
    description: "Remettre la vaisselle propre dans les placards.",
    category: "cuisine",
    minAge: 12,
    roles: ["ado", "parent", "adulte"],
    baseFrequency: "quotidienne",
    estimatedMinutes: 15,
    difficulty: 2,
    householdSizeMin: 3,
    preferredDayOffset: 0,
    indirectCostPerMonth: 8,
    points: 18
  },
  {
    id: "tpl-countertops",
    title: "Essuyer la table et les plans de travail",
    description: "Nettoyer vite la cuisine apres le repas du soir.",
    category: "cuisine",
    minAge: 11,
    roles: ["ado", "parent", "adulte"],
    baseFrequency: "quotidienne",
    estimatedMinutes: 10,
    difficulty: 1,
    preferredDayOffset: 0,
    points: 10
  },
  {
    id: "tpl-bathroom",
    title: "Nettoyer la salle de bain",
    description: "Lavabo, miroir, douche et petite desinfection.",
    category: "hygiene",
    minAge: 15,
    roles: ["ado", "parent", "adulte"],
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 30,
    difficulty: 3,
    preferredDayOffset: 4,
    indirectCostPerMonth: 15,
    points: 30
  },
  {
    id: "tpl-lavabo",
    title: "Nettoyer lavabo et miroir",
    description: "Petit entretien rapide pour garder la salle de bain propre.",
    category: "hygiene",
    minAge: 13,
    roles: ["ado", "parent", "adulte"],
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 12,
    difficulty: 2,
    preferredDayOffset: 1,
    points: 16
  },
  {
    id: "tpl-shopping",
    title: "Planifier les courses",
    description: "Verifier les stocks et preparer une liste avant achat.",
    category: "courses",
    minAge: 18,
    roles: ["parent", "adulte"],
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 25,
    difficulty: 3,
    householdSizeMin: 2,
    preferredDayOffset: 1,
    indirectCostPerMonth: 40,
    points: 28
  },
  {
    id: "tpl-stock-check",
    title: "Faire l'inventaire des placards",
    description: "Lister les basics manquants pour eviter le gaspillage et les doublons.",
    category: "courses",
    minAge: 16,
    roles: ["ado", "parent", "adulte"],
    householdSizeMin: 3,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 18,
    difficulty: 2,
    preferredDayOffset: 0,
    indirectCostPerMonth: 20,
    points: 18
  },
  {
    id: "tpl-mealprep",
    title: "Planifier les repas",
    description: "Prevoir les repas de la semaine pour limiter les achats impulsifs.",
    category: "budget",
    minAge: 18,
    roles: ["parent", "adulte"],
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 30,
    difficulty: 3,
    householdSizeMin: 3,
    preferredDayOffset: 6,
    indirectCostPerMonth: 55,
    points: 32
  },
  {
    id: "tpl-batch-cooking",
    title: "Batch cooking du week-end",
    description: "Preparer deux bases de repas pour alleger les soirs charges.",
    category: "cuisine",
    minAge: 17,
    roles: ["ado", "parent", "adulte"],
    householdSizeMin: 3,
    childrenCountMin: 1,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 55,
    difficulty: 4,
    preferredDayOffset: 6,
    indirectCostPerMonth: 60,
    points: 42
  },
  {
    id: "tpl-simple-dinner",
    title: "Preparer un diner simple",
    description: "Pates, salade composee ou soupe maison avec aide minimale.",
    category: "cuisine",
    minAge: 14,
    roles: ["ado", "parent", "adulte"],
    householdSizeMin: 2,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 30,
    difficulty: 3,
    preferredDayOffset: 2,
    points: 24
  },
  {
    id: "tpl-laundry",
    title: "Lancer une lessive optimisee",
    description: "Regrouper le linge et utiliser un cycle adapte.",
    category: "entretien",
    minAge: 16,
    roles: ["ado", "parent", "adulte"],
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 20,
    difficulty: 2,
    householdSizeMin: 3,
    preferredDayOffset: 1,
    indirectCostPerMonth: 18,
    points: 22
  },
  {
    id: "tpl-fold-laundry",
    title: "Plier et repartir le linge",
    description: "Classer le linge propre pour eviter l'accumulation sur une chaise.",
    category: "entretien",
    minAge: 12,
    roles: ["ado", "parent", "adulte"],
    householdSizeMin: 3,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 25,
    difficulty: 2,
    preferredDayOffset: 2,
    indirectCostPerMonth: 12,
    points: 20
  },
  {
    id: "tpl-change-sheets",
    title: "Changer les draps",
    description: "Relancer la chambre avec des draps propres et aeres.",
    category: "hygiene",
    minAge: 15,
    roles: ["ado", "parent", "adulte"],
    householdSizeMin: 2,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 20,
    difficulty: 2,
    preferredDayOffset: 5,
    points: 18
  },
  {
    id: "tpl-admin",
    title: "Verifier les papiers et rendez-vous",
    description: "Factures, messages ecole, assurance et agenda familial.",
    category: "administratif",
    minAge: 18,
    roles: ["parent", "adulte"],
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 25,
    difficulty: 4,
    childrenCountMin: 1,
    preferredDayOffset: 2,
    points: 24
  },
  {
    id: "tpl-budget-review",
    title: "Revue budget du foyer",
    description: "Verifier ecarts, depenses evitables et objectif d'epargne.",
    category: "budget",
    minAge: 18,
    roles: ["parent", "adulte"],
    householdSizeMin: 2,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 20,
    difficulty: 4,
    preferredDayOffset: 6,
    indirectCostPerMonth: 70,
    points: 26
  },
  {
    id: "tpl-family-calendar",
    title: "Synchroniser le calendrier familial",
    description: "Ecole, activites, garde, rendez-vous et jours charges.",
    category: "administratif",
    minAge: 18,
    roles: ["parent", "adulte"],
    childrenCountMin: 1,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 18,
    difficulty: 3,
    preferredDayOffset: 6,
    points: 18
  },
  {
    id: "tpl-fridge-clean",
    title: "Trier le frigo",
    description: "Retirer les produits a finir et relancer une logique anti-gaspillage.",
    category: "courses",
    minAge: 15,
    roles: ["ado", "parent", "adulte"],
    householdSizeMin: 2,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 18,
    difficulty: 2,
    preferredDayOffset: 4,
    indirectCostPerMonth: 15,
    points: 16
  },
  {
    id: "tpl-entry-reset",
    title: "Ranger l'entree",
    description: "Chaussures, sacs, courrier et manteaux a leur place.",
    category: "entretien",
    minAge: 10,
    roles: ["enfant", "ado", "parent", "adulte"],
    householdSizeMin: 2,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 12,
    difficulty: 1,
    preferredDayOffset: 0,
    points: 12
  },
  {
    id: "tpl-stairs",
    title: "Nettoyer l'entree et les escaliers",
    description: "Passage express sur les zones qui se salissent tres vite.",
    category: "menage",
    minAge: 15,
    roles: ["ado", "parent", "adulte"],
    housingTypes: ["maison"],
    roomCountMin: 5,
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 22,
    difficulty: 2,
    preferredDayOffset: 3,
    points: 22
  },
  {
    id: "tpl-plants",
    title: "Arroser plantes et balcon",
    description: "Verifier les plantes interieures et l'espace exterieur leger.",
    category: "entretien",
    minAge: 8,
    roles: ["enfant", "ado", "parent", "adulte"],
    housingTypes: ["appartement", "maison"],
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 10,
    difficulty: 1,
    preferredDayOffset: 5,
    points: 10
  },
  {
    id: "tpl-dog-walk-morning",
    title: "Promener le chien le matin",
    description: "Sortie courte avant l'ecole ou le travail.",
    category: "animaux",
    minAge: 12,
    roles: ["ado", "parent", "adulte"],
    requiresPetType: "chien",
    baseFrequency: "quotidienne",
    estimatedMinutes: 15,
    difficulty: 2,
    preferredDayOffset: 0,
    indirectCostPerMonth: 20,
    points: 16
  },
  {
    id: "tpl-dog-walk-evening",
    title: "Promener le chien le soir",
    description: "Balade plus longue pour la depense du chien.",
    category: "animaux",
    minAge: 12,
    roles: ["ado", "parent", "adulte"],
    requiresPetType: "chien",
    baseFrequency: "quotidienne",
    estimatedMinutes: 25,
    difficulty: 2,
    preferredDayOffset: 0,
    indirectCostPerMonth: 24,
    points: 20
  },
  {
    id: "tpl-litter",
    title: "Nettoyer la litiere",
    description: "Retirer les dechets et remettre de la litiere propre.",
    category: "animaux",
    minAge: 14,
    roles: ["ado", "parent", "adulte"],
    requiresPetType: "chat",
    baseFrequency: "quotidienne",
    estimatedMinutes: 12,
    difficulty: 2,
    preferredDayOffset: 0,
    indirectCostPerMonth: 10,
    points: 16
  },
  {
    id: "tpl-feeding",
    title: "Remplir les gamelles",
    description: "Verifier eau et nourriture des animaux.",
    category: "animaux",
    minAge: 8,
    roles: ["enfant", "ado", "parent", "adulte"],
    requiresPetType: "any",
    baseFrequency: "quotidienne",
    estimatedMinutes: 8,
    difficulty: 1,
    preferredDayOffset: 0,
    points: 8
  },
  {
    id: "tpl-pet-brush",
    title: "Brosser l'animal",
    description: "Petit brossage pour limiter les poils et garder un poil sain.",
    category: "animaux",
    minAge: 10,
    roles: ["enfant", "ado", "parent", "adulte"],
    requiresPetType: "any",
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 12,
    difficulty: 1,
    preferredDayOffset: 5,
    points: 12
  },
  {
    id: "tpl-pet-bedding",
    title: "Laver panier et accessoires",
    description: "Coussin, plaid, gamelles et petit materiel des animaux.",
    category: "animaux",
    minAge: 14,
    roles: ["ado", "parent", "adulte"],
    requiresPetType: "any",
    baseFrequency: "hebdomadaire",
    estimatedMinutes: 18,
    difficulty: 2,
    preferredDayOffset: 5,
    indirectCostPerMonth: 8,
    points: 18
  },
  {
    id: "tpl-routine-evening",
    title: "Routine du soir",
    description: "Cartables, tenue du lendemain, table du petit-dejeuner.",
    category: "routine",
    minAge: 6,
    roles: ["enfant", "ado", "parent", "adulte"],
    baseFrequency: "quotidienne",
    estimatedMinutes: 15,
    difficulty: 2,
    childrenCountMin: 1,
    preferredDayOffset: 0,
    indirectCostPerMonth: 22,
    points: 14
  },
  {
    id: "tpl-morning-reset",
    title: "Routine du matin",
    description: "Relancer la maison en 10 minutes apres le depart de tous.",
    category: "routine",
    minAge: 16,
    roles: ["ado", "parent", "adulte"],
    householdSizeMin: 3,
    baseFrequency: "quotidienne",
    estimatedMinutes: 10,
    difficulty: 1,
    preferredDayOffset: 0,
    points: 10
  }
];

export const categoryColors: Record<string, string> = {
  menage: "#6D5EF4",
  cuisine: "#FF7E6B",
  animaux: "#56C7A1",
  enfants: "#FFBF5A",
  administratif: "#468BFF",
  budget: "#4AB5A4",
  courses: "#FF8DB2",
  hygiene: "#A07BFF",
  entretien: "#3AB0FF",
  routine: "#7AC74F"
};

export const categoryLabels: Record<string, string> = {
  menage: "Menage",
  cuisine: "Cuisine",
  animaux: "Animaux",
  enfants: "Enfants",
  administratif: "Administratif",
  budget: "Budget",
  courses: "Courses",
  hygiene: "Hygiene",
  entretien: "Entretien",
  routine: "Routine"
};
